class VCFtools < FPM::Cookery::Recipe
  description 'A set of tools written in Perl and C++ for working with VCF files, such as those generated by the 1000 Genomes Project.'
  name 'vcftools'
  version '0.1.14'
  revision 0
  homepage 'https://github.com/vcftools/vcftools'
  source "https://github.com/vcftools/vcftools/releases/download/v#{version}/vcftools-#{version}.tar.gz"
  md5 'a110662535651caa6cc8c876216a9f77'

  # Let's install build dependencies first.
  build_depends ['curl', 'gcc', 'g++', 'zlib1g-dev', 'pkg-config']

  # Build:
  def build
    configure :prefix => prefix
    make
  end

  # Install:
  def install
    make :install, 'DESTDIR' => destdir
  end
end
